packages:
  - "apps/*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - unrs-resolver
  - prisma
  - "@prisma/client"
  - "@prisma/engines"
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  bcrypt: false
  sharp: true
  unrs-resolver: true
  prisma: true
  '@prisma/client': true
  '@prisma/engines': true
